apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  description: This task runs npm install to install node dependencies
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      command: [npm]
      args: [install]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  description: This task runs Jasmine unit tests using npx jasmine
  workspaces:
    - name: source
  steps:
    - name: jasmine-test
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      command: [npx]
      args: [jasmine]